/**
 * server/src/models/Alert.js
 *
 * System alerts — generated by intelligence jobs, displayed on dashboards.
 *
 * Alerts have a lifecycle:
 *   active    → newly detected, needs attention
 *   resolved  → condition no longer exists (auto-resolved by next job run)
 *   dismissed → manually dismissed by a user
 *
 * Auto-resolution: each job that creates alerts also resolves stale ones.
 * If consecutive_absence job runs and EMP1001 is no longer absent 3+ days,
 * that alert is automatically set to 'resolved'.
 */

const mongoose = require('mongoose');
const { ALERT_TYPE, ALERT_SEVERITY, ALERT_STATUS } = require('../config/constants');

const alertSchema = new mongoose.Schema(
  {
    type:     { type: String, enum: Object.values(ALERT_TYPE),     required: true, index: true },
    severity: { type: String, enum: Object.values(ALERT_SEVERITY), required: true, index: true },
    status:   { type: String, enum: Object.values(ALERT_STATUS),   default: 'active', index: true },

    // Who or what this alert is about
    employeeCode: { type: String, index: true, default: null },  // null = system-level alert
    employeeName: { type: String, default: null },
    department:   { type: String, default: null },

    // Human-readable content
    title:   { type: String, required: true },
    message: { type: String, required: true },

    // Machine-readable payload — varies by alert type
    // consecutive_absence: { absentDays, fromDate, toDate, dates[] }
    // sync_stale:          { jobName, lastSuccessAt, staleMinutes }
    // sync_failure:        { jobName, consecutiveFailures, lastError }
    // headcount_shortfall: { shift, expected, actual, missing[] }
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Lifecycle tracking
    detectedAt:  { type: Date, default: Date.now },
    resolvedAt:  { type: Date, default: null },
    dismissedAt: { type: Date, default: null },
    dismissedBy: { type: String, default: null },  // user email
  },
  {
    timestamps: true,
    collection: 'system_alerts',
  }
);

// Compound index — used to find and upsert alerts by type + employee
alertSchema.index({ type: 1, employeeCode: 1, status: 1 });
alertSchema.index({ status: 1, severity: 1, detectedAt: -1 });
alertSchema.index({ detectedAt: -1 });

module.exports = mongoose.model('Alert', alertSchema);